name: myoutput
on: workflow_dispatch
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout
      uses: actions/checkout@v4
    - name: Github Context output
      run: echo "{{ toJSON(github) }}"
